language: haskell
before_install:
  - git clone --quiet git://github.com/diagrams/diagrams-core.git diagrams/diagrams-core
  - git clone --quiet git://github.com/diagrams/diagrams-lib.git diagrams/diagrams-lib
  - cd diagrams
  - cabal install diagrams-core/ diagrams-lib/
  - cd ..
notifications:
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-svg\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
